version: '3.1'

services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      KEY: "value" # Replace with your Directus environment variables as needed
      DB_CLIENT: "pg"
      DB_HOST: "dpg-cq5v8fg8fa8c738f11f0-a.oregon-postgres.render.com"
      DB_PORT: 5432
      DB_DATABASE: "directusdb_3ghc"
      DB_USER: "directususer"
      DB_PASSWORD: "GPmdR3Ih6iPYtXXbsyritaSVU7CmPKYn"
    volumes:
      - directus_data:/directus/data

volumes:
  directus_data:
